// Copyright Dustin Carmelo

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 *	class used to declare and define native gameplay tags through macros
 */

// Primary Attributes Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Strength)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Intelligence)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Resilience)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Vigor)

// Secondary Attributes Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_Armor)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_ArmorPenetration)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_BlockChance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_CriticalHitChance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_CriticalHitDamage)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_CriticalHitResistance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_HealthRegeneration)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_ManaRegeneration)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_MaxHealthPoints)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_MaxManaPoints)

// Meta Attribute Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Meta_IncomingXPPoints)

// Input Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_LMB)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_RMB)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_3)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_4)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Passive_1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Passive_2)

// Damage Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Fire)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Lightning)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Arcane)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Physical)

// Resistance Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resistance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resistance_Fire)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resistance_Lightning)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resistance_Arcane)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resistance_Physical)

// Ability Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Attack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Summon)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Fire_FireBolt)

// Cooldown Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Fire_FireBolt)

// Combat Socket Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CombatSocket_Weapon)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CombatSocket_RightHand)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CombatSocket_LeftHand)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CombatSocket_Tail)

// Montage Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Attack_1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Attack_2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Attack_3)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Attack_4)

// Other Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effects_HitReact)

class AURAGAS_API AGASGameplayTags
{
public:
	AGASGameplayTags();
	~AGASGameplayTags();
};
