// Copyright Dustin Carmelo

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 *	class used to declare and define native gameplay tags through macros
 */

// Primary Attributes Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Strength)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Intelligence)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Resilience)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Vigor)

// Secondary Attributes Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_Armor)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_ArmorPenetration)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_BlockChance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_CriticalHitChance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_CriticalHitDamage)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_CriticalHitResistance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_HealthRegeneration)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_ManaRegeneration)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_MaxHealthPoints)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_MaxManaPoints)

// Meta Attribute Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Meta_IncomingXPPoints)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Meta_IncomingForce)

// Input Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_LMB)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_RMB)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_3)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_4)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Passive_1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputTag_Passive_2)

// Damage Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Fire)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Lightning)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Arcane)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Damage_Physical)

// Debuff Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Debuff)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Debuff_Burn)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Debuff_Stun)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Debuff_Arcane)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Debuff_Physical)

// Debuff Tags: Params
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Debuff_Params_Chance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Debuff_Params_Damage)

// Resistance Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Resistance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Resistance_Fire)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Resistance_Lightning)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Resistance_Arcane)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Resistance_Physical)

// Ability Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Attack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Summon)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_HitReact)

// Ability Tags: Status
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Status_Locked)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Status_Eligible)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Status_Unlocked)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Status_Equipped)

// Ability Tags: Types
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Type_Offensive)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Type_Passive)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Type_None)

// Ability Tags: Aura
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Fire_FireBolt)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Fire_FireBlast)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Lightning_Electrocute)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Arcane_ArcaneShards)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Passive) // different from Type_Passive; this one is for GAs, the other is for UI and AbilityInfo
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Passive_HaloOfProtection)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Passive_LifeSiphon)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Passive_ManaSiphon)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Passive_ListenForEvent)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Passive_Buff_HaloWard)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Passive_Buff_LifeSiphon)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Abilities_Passive_Buff_ManaSiphon)

// Cooldown Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Fire_FireBolt)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Fire_FireBlast)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Lightning_Electrocute)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Arcane_ArcaneShards)

// Combat Socket Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CombatSocket_Weapon)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CombatSocket_RightHand)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CombatSocket_LeftHand)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CombatSocket_Tail)

// Montage Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Attack_1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Attack_2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Attack_3)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Attack_4)

// Player Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player_Block_InputPressed)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player_Block_InputHeld)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player_Block_InputReleased)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player_Block_CursorTrace)

// Other Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effects_HitReact)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_StatusEffects_Knockback)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_FireBlast)



class AURAGAS_API AGASGameplayTags
{
public:
	AGASGameplayTags();
	~AGASGameplayTags();
	
	static const TMap<FGameplayTag, FGameplayTag>& GetDamageTypeToResistMap() { return DamageTypeToResistMap; }
	static const TMap<FGameplayTag, FGameplayTag>& GetDamageTypeToDebuffMap() { return DamageTypeToDebuffMap; }
	
private:
	
	static const TMap<FGameplayTag, FGameplayTag> DamageTypeToResistMap;
	static const TMap<FGameplayTag, FGameplayTag> DamageTypeToDebuffMap;
	
};
